spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/miscuglione_db
    username: miscuglione
    password: miscuglione
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
