spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/miscuglione
    username: miscuglione
    password: miscuglione
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  kafka:
    host: localhost:9092
    groupId: foo

server:
  port: 8081